#!/usr/bin/env python3
"""
One-shot extractor: read each /insights/*.html and produce
/src/insights/<slug>.html with YAML frontmatter + body.

Run once during the Eleventy migration. After this is committed, articles
are edited in /src/insights/<slug>.html (frontmatter + body markup) and
/insights/*.html files are regenerated by `npm run build`.

Designed to be idempotent — running twice produces the same output.
"""
import re
import os
import glob
import json
import sys

INSIGHTS_DIR = "insights"
OUT_DIR = "src/insights"


def extract_meta(html, name, regex):
    m = re.search(regex, html)
    if not m:
        raise SystemExit(f"could not find {name} in this article")
    return m.group(1).strip()


def extract_meta_optional(html, regex):
    m = re.search(regex, html)
    return m.group(1).strip() if m else None


def parse_jsonld(html):
    m = re.search(
        r'<script type="application/ld\+json">\s*(\{.*?\})\s*</script>',
        html, re.S
    )
    if not m:
        raise SystemExit("missing JSON-LD")
    return json.loads(m.group(1))


def extract_article_body(html):
    """Body is the <div class="article-body">...</div> content."""
    m = re.search(
        r'<div class="article-body">\s*(.*?)\s*</div>\s*</article>',
        html, re.S
    )
    if not m:
        raise SystemExit("missing article-body")
    body = m.group(1).strip()
    # Normalise indentation: each top-level <p>/<h2>/<ul> gets no indent
    lines = body.splitlines()
    out = []
    for line in lines:
        out.append(line.rstrip())
    return "\n".join(out)


def extract_lead(html):
    m = re.search(r'<p class="article-lead">(.*?)</p>', html, re.S)
    return m.group(1).strip() if m else ""


def extract_meta_spans(html):
    """Extract tag, displayDate, readTime from .article-meta."""
    m = re.search(r'<div class="article-meta">(.*?)</div>', html, re.S)
    if not m:
        return ("AI Governance", "", "")
    spans = re.findall(r'<span(?:\s[^>]*)?>(.*?)</span>', m.group(1), re.S)
    spans = [s.strip() for s in spans]
    tag = spans[0] if len(spans) > 0 else "AI Governance"
    date = spans[1] if len(spans) > 1 else ""
    read = spans[2] if len(spans) > 2 else ""
    # remove any leading "<span class=tag>" wrapper
    tag = re.sub(r'<[^>]+>', '', tag).strip()
    return (tag, date, read)


def extract_cta(html):
    """Pull the CTA section as a structured dict (heading + body + buttons)."""
    m = re.search(
        r'<div class="cta-section">\s*'
        r'<h3>(.*?)</h3>\s*'
        r'<p>(.*?)</p>\s*'
        r'<div class="cta-buttons">(.*?)</div>\s*'
        r'(?:<p class="cta-divider">(.*?)</p>\s*)?'
        r'</div>',
        html, re.S
    )
    if not m:
        return None
    heading, body, btns_html, divider = m.groups()
    btns = []
    for bm in re.finditer(
        r'<a\s+href="([^"]+)"\s+class="(cta-button(?:-secondary)?)"\s+'
        r'onclick="(gtag\([^"]*\))">([^<]+)</a>',
        btns_html, re.S
    ):
        href, cls, onclick, label = bm.groups()
        btns.append({
            "href": href,
            "class": cls.strip(),
            "onclick": onclick,
            "label": label.strip(),
        })
    return {
        "heading": heading.strip(),
        "body": body.strip(),
        "buttons": btns,
        "divider": (divider or "").strip(),
    }


def extract_related(html):
    m = re.search(
        r'<div class="related">\s*<h3>Related Articles</h3>\s*'
        r'<div class="related-list">(.*?)</div>\s*</div>',
        html, re.S
    )
    if not m:
        return []
    items = re.findall(
        r'<a href="([^"]+)\.html" class="related-item">\s*'
        r'<h4>(.*?)</h4>\s*<p>(.*?)</p>\s*</a>',
        m.group(1), re.S
    )
    return [
        {"slug": slug.strip(), "title": title.strip(), "description": desc.strip()}
        for slug, title, desc in items
    ]


def extract_linkedin_url(html):
    """The 'Originally published on LinkedIn' anchor."""
    m = re.search(
        r'<a\s+href="([^"]+)"[^>]*>\s*<svg[^>]*>(?:[^<]|<[^/])*?</svg>\s*Originally published on LinkedIn',
        html, re.S
    )
    return m.group(1) if m else None


def yaml_escape(s):
    """Conservative YAML string escape — wrap in double quotes and escape."""
    if s is None:
        return ""
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def convert_one(path):
    name = os.path.basename(path)
    slug = name.replace(".html", "")
    html = open(path).read()

    title = extract_meta(html, "title", r'<title>([^<]+?)</title>')
    title = re.sub(r"\s*\|\s*Steven Wensley\s*$", "", title).strip()
    description = extract_meta(html, "description",
        r'<meta name="description" content="([^"]+)"')
    og_title = extract_meta_optional(html,
        r'<meta property="og:title" content="([^"]+)"')
    og_desc = extract_meta_optional(html,
        r'<meta property="og:description" content="([^"]+)"')
    tw_title = extract_meta_optional(html,
        r'<meta name="twitter:title" content="([^"]+)"')
    tw_desc = extract_meta_optional(html,
        r'<meta name="twitter:description" content="([^"]+)"')
    canonical = extract_meta_optional(html,
        r'<link rel="canonical" href="([^"]+)"')

    jsonld = parse_jsonld(html)
    headline = jsonld.get("headline", title)
    date_published = jsonld.get("datePublished", "")
    date_modified = jsonld.get("dateModified", "")

    tag, display_date, read_time = extract_meta_spans(html)
    lead = extract_lead(html)
    linkedin = extract_linkedin_url(html)
    related = extract_related(html)
    cta = extract_cta(html)
    body = extract_article_body(html)

    # Build frontmatter
    fm = ["---"]
    fm.append("layout: article.njk")
    fm.append(f"title: {yaml_escape(title)}")
    fm.append(f"headline: {yaml_escape(headline)}")
    fm.append(f"description: {yaml_escape(description)}")
    if og_title and og_title != title:
        fm.append(f"ogTitle: {yaml_escape(og_title)}")
    if og_desc and og_desc != description:
        fm.append(f"ogDescription: {yaml_escape(og_desc)}")
    if tw_title and tw_title != (og_title or title):
        fm.append(f"twitterTitle: {yaml_escape(tw_title)}")
    if tw_desc and tw_desc != (og_desc or description):
        fm.append(f"twitterDescription: {yaml_escape(tw_desc)}")
    fm.append("ogType: article")
    fm.append(f"slug: {slug}")
    fm.append(f"permalink: /insights/{slug}.html")
    fm.append(f"canonical: {yaml_escape(canonical)}")
    fm.append("hreflang:")
    fm.append(f'  - {{ lang: "en", href: "{canonical}" }}')
    fm.append(f'  - {{ lang: "x-default", href: "{canonical}" }}')
    fm.append(f"datePublished: {date_published}")
    fm.append(f"dateModified: {date_modified}")
    fm.append(f"tag: {yaml_escape(tag)}")
    fm.append(f"displayDate: {yaml_escape(display_date)}")
    fm.append(f"readTime: {yaml_escape(read_time)}")
    fm.append(f"lead: {yaml_escape(lead)}")
    if linkedin:
        fm.append(f"linkedinUrl: {yaml_escape(linkedin)}")
    fm.append("activeNav: insights")
    fm.append("jsonLd:")
    fm.append('  "@context": "https://schema.org"')
    fm.append('  "@type": "Article"')
    fm.append(f"  headline: {yaml_escape(headline)}")
    fm.append(f"  description: {yaml_escape(description)}")
    fm.append("  author:")
    fm.append('    "@type": "Person"')
    fm.append('    name: "Steven Seidenfaden Wensley"')
    fm.append("  publisher:")
    fm.append('    "@type": "Organization"')
    fm.append('    name: "Steven Wensley"')
    fm.append('    url: "https://stevenwensley.com"')
    fm.append(f'  datePublished: "{date_published}"')
    fm.append(f'  dateModified: "{date_modified}"')
    fm.append('  image: "https://stevenwensley.com/og-image.png"')
    fm.append("related:")
    for r in related:
        fm.append(f'  - {{ slug: "{r["slug"]}", title: {yaml_escape(r["title"])}, description: {yaml_escape(r["description"])} }}')
    if cta:
        fm.append("cta:")
        fm.append(f"  heading: {yaml_escape(cta['heading'])}")
        fm.append(f"  body: {yaml_escape(cta['body'])}")
        if cta["divider"]:
            fm.append(f"  divider: {yaml_escape(cta['divider'])}")
        fm.append("  buttons:")
        for b in cta["buttons"]:
            fm.append(
                f'    - {{ href: {yaml_escape(b["href"])}, '
                f'class: {yaml_escape(b["class"])}, '
                f'onclick: {yaml_escape(b["onclick"])}, '
                f'label: {yaml_escape(b["label"])} }}'
            )
    fm.append("---")

    out_path = os.path.join(OUT_DIR, slug + ".html")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(fm))
        f.write("\n\n")
        f.write(body)
        f.write("\n")
    return out_path


if __name__ == "__main__":
    files = sorted(glob.glob(f"{INSIGHTS_DIR}/*.html"))
    if not files:
        sys.exit("no insights articles found")
    for f in files:
        out = convert_one(f)
        print(f"  {f} → {out}")
    print(f"Converted {len(files)} articles to {OUT_DIR}")
