#!/usr/bin/env python3
"""
Re-fetch self-hosted fonts from Google Fonts.

Run this when:
  - Adding a new weight/style/character-range
  - Updating to newer font version
  - Verifying nothing has been tampered with

Usage:
  python3 scripts/fetch-fonts.py

Writes /fonts/<font-family>-<weight>[-italic]-<range>.woff2 plus
/fonts/fonts.css with @font-face declarations pointing at the local
files. Idempotent: skips download if file exists.

Fonts (OFL licensed — redistribution permitted):
  - DM Serif Display 400, 400 italic
  - Space Grotesk 300, 400, 500, 600, 700
"""
import urllib.request, re, os, sys

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
)

# Modern Safari UA gets woff2 from Google Fonts (older UAs get TTF/EOT).
GFONTS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=DM+Serif+Display:ital@0;1"
    "&family=Space+Grotesk:wght@300;400;500;600;700"
    "&display=swap"
)

OUT_DIR = "fonts"
HEADER = """/* Self-hosted Google Fonts — DM Serif Display + Space Grotesk.
 * Generated by /scripts/fetch-fonts.py.
 * Source: GFONTS_URL_GOES_HERE
 * Re-run that script to refresh / pin a new version.
 */

"""


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req).read()


def main():
    css = fetch(GFONTS_URL).decode("utf-8")
    blocks = re.findall(r"(/\*[^*]+\*/\s*@font-face\s*\{[^}]+\})", css, re.S)
    if not blocks:
        sys.exit("Could not parse Google Fonts CSS")

    os.makedirs(OUT_DIR, exist_ok=True)
    url_re = re.compile(r"url\(([^)]+)\)")
    ff_re = re.compile(r"font-family:\s*'([^']+)'")
    fs_re = re.compile(r"font-style:\s*(\w+)")
    fw_re = re.compile(r"font-weight:\s*(\d+)")
    range_re = re.compile(r"/\*\s*([\w-]+)\s*\*/")

    local_blocks = []
    total = 0
    for block in blocks:
        url = url_re.search(block).group(1)
        fam = ff_re.search(block).group(1)
        style = fs_re.search(block).group(1)
        weight = fw_re.search(block).group(1)
        rng = range_re.search(block).group(1)
        fam_slug = fam.lower().replace(" ", "-")
        fname = f"{fam_slug}-{weight}{'-italic' if style == 'italic' else ''}-{rng}.woff2"
        out = os.path.join(OUT_DIR, fname)
        if not os.path.exists(out):
            data = fetch(url)
            open(out, "wb").write(data)
            total += len(data)
            print(f"  + {fname} ({len(data):,} bytes)")
        else:
            print(f"  = {fname} (cached)")
        local_blocks.append(block.replace(url, f"/fonts/{fname}"))

    out_css = HEADER.replace("GFONTS_URL_GOES_HERE", GFONTS_URL) + "\n\n".join(local_blocks) + "\n"
    open(os.path.join(OUT_DIR, "fonts.css"), "w").write(out_css)
    print(f"\nWrote {OUT_DIR}/fonts.css ({len(out_css)} chars)")
    print(f"Total downloaded: {total:,} bytes across {len(local_blocks)} files")


if __name__ == "__main__":
    main()
